- name: Install python module for work with certbot
  ansible.builtin.apt:
    pkg:
      - python3-certbot-dns-cloudflare

- name: Create config
  ansible.builtin.template:
    src: cloudflare.ini.j2
    dest: "/etc/letsencrypt/cloudflare.ini"
    mode: '0640'

- name: Create new SSL
  ansible.builtin.command:
    cmd: >
      certbot certonly --agree-tos -n -m {{ certbot_cloudflare_email }} --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      -d {{ domain }} -d *.{{ domain }}
    creates: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
  loop: "{{ certbot_domain }}"
  loop_control:
    loop_var: domain
